//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom1_QuanLyHocVu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUONGTRINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUONGTRINH()
        {
            this.CHUONGTRINHMONHOCs = new HashSet<CHUONGTRINHMONHOC>();
            this.DAMNHIEMMONs = new HashSet<DAMNHIEMMON>();
            this.KHOAHOCs = new HashSet<KHOAHOC>();
        }
    
        public string MaChuongTrinh { get; set; }
        public string TenChuongTrinh { get; set; }
        public string MaBacHoc { get; set; }
        public string MaKhoa { get; set; }
        public string MaGiaoVien_GiamDocCT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUONGTRINHMONHOC> CHUONGTRINHMONHOCs { get; set; }
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual KHOA KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAMNHIEMMON> DAMNHIEMMONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOAHOC> KHOAHOCs { get; set; }
    }
}
