//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom1_QuanLyHocVu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAMNHIEMMON
    {
        public string MaChuongTrinh { get; set; }
        public string MaMonHoc { get; set; }
        public string MaGiaoVien { get; set; }
        public Nullable<int> CoLaDamNhiemChinh { get; set; }
    
        public virtual CHUONGTRINH CHUONGTRINH { get; set; }
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
