//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom1_QuanLyHocVu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOAHOCMON
    {
        public string MaKhoaHoc { get; set; }
        public string MaMonHoc { get; set; }
        public string MaGiaoVien_day { get; set; }
        public string MaPhong { get; set; }
        public string MaThu { get; set; }
        public int ID { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual KHOAHOC KHOAHOC { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
