//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom1_QuanLyHocVu.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyHocVuEntities : DbContext
    {
        public QuanLyHocVuEntities()
            : base("name=QuanLyHocVuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUONGTRINH> CHUONGTRINHs { get; set; }
        public virtual DbSet<CHUONGTRINHMONHOC> CHUONGTRINHMONHOCs { get; set; }
        public virtual DbSet<DAMNHIEMMON> DAMNHIEMMONs { get; set; }
        public virtual DbSet<GIAOVIEN> GIAOVIENs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<KHOAHOC> KHOAHOCs { get; set; }
        public virtual DbSet<MONHOC> MONHOCs { get; set; }
        public virtual DbSet<KHOAHOCMON> KHOAHOCMONs { get; set; }
    }
}
